package com.support.server.supportrosterserver.config;

import jakarta.annotation.PostConstruct;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class WorkspaceSchemaBootstrap {

    private final JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void ensureSharedShiftDefinitionSchema() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS workspace_shift_definition_team_rel (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                shift_definition_id BIGINT NOT NULL REFERENCES workspace_shift_definition (id),
                team_id BIGINT NOT NULL REFERENCES workspace_team (id),
                create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """);

        jdbcTemplate.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_shift_definition_team_rel
            ON workspace_shift_definition_team_rel (shift_definition_id, team_id)
            """);

        jdbcTemplate.execute("""
            CREATE INDEX IF NOT EXISTS idx_workspace_shift_definition_team_rel_team
            ON workspace_shift_definition_team_rel (team_id, shift_definition_id)
            """);

        jdbcTemplate.execute("""
            INSERT INTO workspace_shift_definition_team_rel (shift_definition_id, team_id)
            SELECT id, team_id
            FROM workspace_shift_definition
            WHERE team_id IS NOT NULL
            ON CONFLICT DO NOTHING
            """);
    }
}