CREATE TABLE IF NOT EXISTS workspace_access_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_code VARCHAR(64) NOT NULL,
    auth_required BOOLEAN NOT NULL DEFAULT TRUE,
    deleted INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_access_policy_page_code
    ON workspace_access_policy (page_code)
    WHERE deleted = 0;

INSERT INTO workspace_access_policy (page_code, auth_required)
SELECT seed.page_code, seed.auth_required
FROM (
    VALUES
        ('overview', FALSE),
        ('roster', TRUE),
        ('staff', TRUE),
        ('shifts', TRUE),
        ('validation', TRUE),
        ('import-export', TRUE)
) AS seed(page_code, auth_required)
WHERE NOT EXISTS (
    SELECT 1
    FROM workspace_access_policy existing
    WHERE existing.page_code = seed.page_code
      AND existing.deleted = 0
);

DROP TRIGGER IF EXISTS trg_workspace_access_policy_update_time ON workspace_access_policy;
CREATE TRIGGER trg_workspace_access_policy_update_time
    BEFORE UPDATE ON workspace_access_policy
    FOR EACH ROW
    EXECUTE FUNCTION set_update_time();
